// <auto-generated />
namespace WebFront.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class Addingbankinginformationtouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addingbankinginformationtouser));
        
        string IMigrationMetadata.Id
        {
            get { return "201312060134297_Adding banking information to user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
